spring.application.name=ecommerce
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommerce}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:kabeldata}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=${JWT_SECRET:ThisIsADevelopmentSecretKeyThatMustBeLongEnough123456}
app.jwt.access-token-expiration=PT2H
app.pagination.default-page-size=10
app.pagination.max-page-size=100
app.storage.product-images-dir=${PRODUCT_IMAGES_DIR:uploads/products}

server.error.include-stacktrace=never

# Resend API key (set via RESEND_API_KEY environment variable)
resend.api.key=${RESEND_API_KEY:}
spring.security.oauth2.client.registration.google.client-id=${google.client-id}
spring.security.oauth2.client.registration.google.client-secret=${google.client-secret}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Frontend Redirect URI for OAuth2 Login success redirection
app.oauth2.frontend-redirect-uri=${OAUTH2_FRONTEND_REDIRECT_URI:http://localhost:3000/oauth2/redirect}

