ALTER TABLE users MODIFY COLUMN password VARCHAR(255) NULL;
ALTER TABLE users MODIFY COLUMN phone_number VARCHAR(30) NULL;
ALTER TABLE users ADD COLUMN provider VARCHAR(50);
ALTER TABLE users ADD COLUMN provider_id VARCHAR(255);
